### ISSUE TITLE
"Medication" resource type

### ISSUE THREAD

**Issue by eric-chou** [AHRQ-CDS/CQL-Testing-Framework#2]
Hello again,

thanks for your previous help for the first issue about the "dosage" attribute. Another element we are trying to implement involves the ["Medication" resource type](https://hl7.org/fhir/STU3/medication.html). Specifically from this we would like to access items from the "ingredient" part of this where we extract the "amount" of a medication. FHIR provides an example of this for a medication statement [here](https://hl7.org/fhir/STU3/medicationstatementexample1.json.html) where we can see the "Tylenol PM" medication specified as an ingredient named "Acetaminophen 500 MG" which has an amount 500 milligrams.

We notice that the test cases support specifying the "medication[x]" portion of [MedicationStatements](https://hl7.org/fhir/STU3/medicationstatement.html) via the CodeableConcept, but it looks like for the functionality above it would need to be done through a reference to a full medication object, which doesn't currently seem to be a supported resource type. Is this correct? If so, what steps would you suggest for implementing the use of full medication objects?

Thank you for your time!
-Eric

**Comment by dwwinters** [comment]
You'd have to implement a `handleMedication` function and include it in the `handleResource` function (https://github.com/AHRQ-CDS/CQL-Testing-Framework/blob/master/src/loadYamlTestCases.js#L181).  You could probably model it after what has already been implemented, but will want to double-check which elements you want to be able to specify in YAML and what your default values will be.

**Comment by eric-chou** [comment]
Ok, so I attempted to implement a handleMedication function (see our forked version of the loadYamlTestCases.js at [line 333](https://github.com/dbmi-pitt/CQL-Testing-Framework/blob/08c980fdd067692facfd2d6f6452bdc0871b4d15/src/loadYamlTestCases.js#L333)) and added it to the handleResource function on that fork as well. From here though, I looked to the next step of referencing this resource type in the test case YAML files and in the CQL syntax, and it looks like it's here where it hits a roadblock where I'm not sure how to proceed.

For reference, here's how I structured the YAML for the "medication" resource type:

```
  resourceType: Medication
  code: RXNORM#283672 Citalopram 10 MG Oral Tablet
  ingredient:
    -
      amount:
        numerator:
          value: 10
        denominator:
          value: 1
```

I set up the following basic CQL function to attempt to reference it ("Citaloprams VS" refers to a value set of citalopram concept codes, which includes the Citalopram Medication in the YAML above). 

```
define "List Citaloprams":
  [Medication: "Citaloprams VS"] M
  return {
    M
  }
```

This function returns empty, though - no errors, just an empty array is returned. So I was wondering if you had any pointers on how to proceed? i.e. is there anything off in the loadYamlTestCases javascript that you observed, or is there something that needs to be fixed with the YAML/CQL part of it?

Another thing that I noticed was that the Medication resource type we are trying to implement does seem to differ in that in that examples provided by HL7, it seems that for each MedicationStatement, the referenced Medication resides in a "contained" array. This can be seen at the top of [this example](https://hl7.org/fhir/2018Jan/medicationstatementexample2.json.html). Here, the ID "med0309" is used for both this "contained" Medication ID and then referenced again under the "medicationReference" part of the MedicationStatement. Do you think the usage of "contained" here should complicate or change the approach for incorporating Medication resource types with MedicationStatements?

**Comment by dwwinters** [comment]
Hi @eric-chou, just wanted to let you know that I'm looking at your questions.  I've got a couple of thoughts on what's going on, but want to confirm a few things first.

**Comment by dwwinters** [comment]
@eric-chou: One issue we noticed in your implementation is that the `resourceType` property isn't set within handleMedication(). We think that the retrieve likely won't return anything if this isn't set.

**Comment by eric-chou** [comment]
@dwwinters I just added that property and it looks like fixing that oversight did the trick. Thanks a lot for your help!
